// <auto-generated />
using System;
using DanceBlocks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DanceBlocks.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190701152411_Added-seed-data-for-db-first-run")]
    partial class Addedseeddatafordbfirstrun
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DanceBlocks.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rhythm"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Smooth"
                        });
                });

            modelBuilder.Entity("DanceBlocks.Models.DanceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<int>("DanceTypeId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DanceTypeId");

                    b.ToTable("DanceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DanceTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DanceTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DanceTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DanceTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DanceTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            DanceTypeId = 6
                        });
                });

            modelBuilder.Entity("DanceBlocks.Models.DanceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DanceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rumba"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cha Cha"
                        },
                        new
                        {
                            Id = 3,
                            Name = "East Coast Swing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Waltz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tango"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Foxtrot"
                        });
                });

            modelBuilder.Entity("DanceBlocks.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2019, 7, 1, 11, 24, 11, 25, DateTimeKind.Local).AddTicks(3373),
                            Name = "Intro",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2019, 7, 1, 11, 24, 11, 25, DateTimeKind.Local).AddTicks(4203),
                            Name = "Intermediate",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2019, 7, 1, 11, 24, 11, 25, DateTimeKind.Local).AddTicks(4215),
                            Name = "Advanced",
                            StudentId = 4
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2019, 7, 1, 11, 24, 11, 25, DateTimeKind.Local).AddTicks(4219),
                            Name = "Lesson 6",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("DanceBlocks.Models.LessonStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LessonId");

                    b.Property<int>("StepId");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StepId");

                    b.ToTable("LessonSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LessonId = 1,
                            StepId = 1
                        },
                        new
                        {
                            Id = 2,
                            LessonId = 1,
                            StepId = 4
                        },
                        new
                        {
                            Id = 3,
                            LessonId = 1,
                            StepId = 7
                        },
                        new
                        {
                            Id = 4,
                            LessonId = 1,
                            StepId = 10
                        },
                        new
                        {
                            Id = 5,
                            LessonId = 2,
                            StepId = 2
                        },
                        new
                        {
                            Id = 6,
                            LessonId = 2,
                            StepId = 5
                        },
                        new
                        {
                            Id = 7,
                            LessonId = 2,
                            StepId = 8
                        },
                        new
                        {
                            Id = 8,
                            LessonId = 2,
                            StepId = 11
                        },
                        new
                        {
                            Id = 9,
                            LessonId = 4,
                            StepId = 3
                        },
                        new
                        {
                            Id = 10,
                            LessonId = 4,
                            StepId = 6
                        },
                        new
                        {
                            Id = 11,
                            LessonId = 4,
                            StepId = 9
                        },
                        new
                        {
                            Id = 12,
                            LessonId = 4,
                            StepId = 12
                        },
                        new
                        {
                            Id = 13,
                            LessonId = 4,
                            StepId = 8
                        },
                        new
                        {
                            Id = 14,
                            LessonId = 4,
                            StepId = 5
                        },
                        new
                        {
                            Id = 15,
                            LessonId = 4,
                            StepId = 11
                        },
                        new
                        {
                            Id = 16,
                            LessonId = 4,
                            StepId = 2
                        });
                });

            modelBuilder.Entity("DanceBlocks.Models.SkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Level");

                    b.HasKey("Id");

                    b.ToTable("SkillLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "Beginner"
                        },
                        new
                        {
                            Id = 2,
                            Level = "Intermediate"
                        },
                        new
                        {
                            Id = 3,
                            Level = "Advanced"
                        });
                });

            modelBuilder.Entity("DanceBlocks.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DanceTypeId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("SkillLevelId");

                    b.HasKey("Id");

                    b.HasIndex("DanceTypeId");

                    b.HasIndex("SkillLevelId");

                    b.ToTable("Steps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DanceTypeId = 6,
                            Description = "Lead: Starting with left foot, take 2 steps forward then a side step to the left and close. Follow: Starting with the right foot, take 2 steps backwards then a side step to the right and close.",
                            Name = "Magic Step",
                            SkillLevelId = 1
                        },
                        new
                        {
                            Id = 2,
                            DanceTypeId = 6,
                            Description = "Lead: Look over left shoulder and rotate feet to the left keeping body in frame. Starting with left foot, take 2 horizontal steps then a side step and close while rotating back to normal position. Follow: Look over right shoulder and rotate feet to the right keeping body in frame Starting with the right foot, take 2 Horizontal steps then a side step and close while rotating to normal position.",
                            Name = "Promenade",
                            SkillLevelId = 2
                        },
                        new
                        {
                            Id = 3,
                            DanceTypeId = 6,
                            Description = "*Box Timing* Lead: Starting with left foot, take 1 step forward, a half diagnal step w/right foot into a promenade left step. Finish with brushing right step and close box step.  Follow: Starting with the right foot, take 1 step backward, a half diagnal step w/ left foot into a promenade right step. Finish with brusing left step and close box step.",
                            Name = "Basic Twinkle ",
                            SkillLevelId = 3
                        },
                        new
                        {
                            Id = 4,
                            DanceTypeId = 5,
                            Description = "Lead: Starting with left foot, take 3 steps forward then a side step to the right and close left foot but do not place weight on it. Follow: Starting with the right foot, take 3 steps backwards then a side step to the right and close right foot but do not place weight on it.",
                            Name = "Tango Basic",
                            SkillLevelId = 1
                        },
                        new
                        {
                            Id = 5,
                            DanceTypeId = 5,
                            Description = "Lead: Procede with Tango Basic. While closing, rotate head and toes left into promenade position.  Starting with left foot, take 2 steps in promenade, rotate partner to close then side step to the right and close left foot but do not place weight on it. Follow: Procede with Tango Basic. While closing, rotate head and toes right into promenade position. Starting with the right foot, take 2 steps in promenade, swivel to close then side step to the left and close right foot but do not place weight on it.",
                            Name = "Tango Promenade",
                            SkillLevelId = 2
                        },
                        new
                        {
                            Id = 6,
                            DanceTypeId = 5,
                            Description = "Lead: Starting with left foot, take 2 steps forward. Beginning on 3rd step while rotating right take four quick rock steps. Finish with Tango Basic. Follow: Starting with the right foot, take 2 steps backwards. Beginning on 3rd step while rotating right take four quick rock steps. Finish with Tango Basic.",
                            Name = "Tango Double Spin Turn",
                            SkillLevelId = 3
                        },
                        new
                        {
                            Id = 7,
                            DanceTypeId = 4,
                            Description = "Lead: Starting with left foot, take 1 steps forward. Side step to right and close left foot. Starting with right foot, take one step backwards. Side step to left and close right foot.  Follow: Starting with right foot, take 1 steps backwards. Side step to left and close right foot. Starting with Left Foot, take one step forwards. Side step to right and close left foot.",
                            Name = "Waltz Box",
                            SkillLevelId = 1
                        },
                        new
                        {
                            Id = 8,
                            DanceTypeId = 4,
                            Description = "Lead: Rotate head and toes left into promenade positon. Starting with left foot, take 1 step in promenade. Hold for 2 counts. Step with right foot in promenade, rotate to close, and side step to left and close right foot.  Follow: Rotate head and toes right into promenade positon. Starting with right foot, take 1 step in promenade. Hold for 2 counts. Step with left foot in promenade, rotate to close and side step to right and close left foot.",
                            Name = "Waltz Promenade",
                            SkillLevelId = 2
                        },
                        new
                        {
                            Id = 9,
                            DanceTypeId = 4,
                            Description = "Lead: Starting with left foot, take 1 steps forward. Side step to right and close left foot. Starting with right foot; side step, open break with left foot and return weight to right foot. Side step to left foot and lift left arm. Open break to right foot as partner passes under left arm into turn. Return weight to left foot, lower left arm and side step to right. Hold for 2 counts while reconnecting with partner. Follow: Starting with right foot, take 1 steps backwards. Side step to left and close right foot. Starting with Left Foot; side step, open break with right foot and return weight to left foot. Side step to right foot and connect right hand into partners left hand. With left foot, step outside partner and on right foot spin back closed to partner.  Side step to left.",
                            Name = "Open Break Underarm Turn",
                            SkillLevelId = 3
                        },
                        new
                        {
                            Id = 10,
                            DanceTypeId = 3,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque sit amet porttitor eget dolor morbi non arcu. Ante in nibh mauris cursus mattis. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Tortor aliquam nulla facilisi cras fermentum.",
                            Name = "Triple Time Swing Basic",
                            SkillLevelId = 1
                        },
                        new
                        {
                            Id = 11,
                            DanceTypeId = 3,
                            Description = "Eros in cursus turpis massa tincidunt dui ut ornare lectus. Netus et malesuada fames ac turpis. Magna fermentum iaculis eu non diam phasellus. Cras tincidunt lobortis feugiat vivamus at augue. Arcu ac tortor dignissim convallis aenean et. Ipsum dolor sit amet consectetur adipiscing.",
                            Name = "Underarm Turn",
                            SkillLevelId = 2
                        },
                        new
                        {
                            Id = 12,
                            DanceTypeId = 3,
                            Description = "Eu volutpat odio facilisis mauris sit amet massa vitae tortor. Odio ut enim blandit volutpat maecenas volutpat blandit. Et malesuada fames ac turpis egestas sed tempus urna et. Molestie ac feugiat sed lectus. Eget mauris pharetra et ultrices. Justo laoreet sit amet cursus sit. Interdum consectetur libero id faucibus nisl tincidunt eget nullam. Venenatis tellus in metus vulputate eu scelerisque. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Elit scelerisque mauris pellentesque pulvinar pellentesque. Morbi tincidunt augue interdum velit euismod in pellentesque. Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed.",
                            Name = "Walks and Kicks",
                            SkillLevelId = 3
                        },
                        new
                        {
                            Id = 13,
                            DanceTypeId = 2,
                            Description = "Ac orci phasellus egestas tellus. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Est sit amet facilisis magna etiam tempor orci eu lobortis. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. In est ante in nibh. Suscipit tellus mauris a diam maecenas sed enim. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Placerat duis ultricies lacus sed turpis tincidunt id aliquet risus. Varius sit amet mattis vulputate enim nulla aliquet. Id velit ut tortor pretium viverra.",
                            Name = "Cha Cha Basic",
                            SkillLevelId = 1
                        },
                        new
                        {
                            Id = 14,
                            DanceTypeId = 2,
                            Description = "Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Congue mauris rhoncus aenean vel. Eget duis at tellus at urna condimentum. In hac habitasse platea dictumst vestibulum. Quis hendrerit dolor magna eget est. At ultrices mi tempus imperdiet nulla malesuada pellentesque. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Tempus imperdiet nulla malesuada pellentesque. Faucibus scelerisque eleifend donec pretium vulputate sapien.",
                            Name = "Crossover Breaks",
                            SkillLevelId = 2
                        },
                        new
                        {
                            Id = 15,
                            DanceTypeId = 2,
                            Description = "Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Vitae justo eget magna fermentum iaculis eu non. Ultrices gravida dictum fusce ut placerat orci. Consectetur lorem donec massa sapien faucibus et molestie. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Sed arcu non odio euismod lacinia. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Nunc sed blandit libero volutpat sed cras ornare arcu dui. At consectetur lorem donec massa sapien faucibus. Tortor pretium viverra suspendisse potenti nullam ac tortor. Blandit volutpat maecenas volutpat blandit aliquam etiam erat.",
                            Name = "Backspot Turn",
                            SkillLevelId = 3
                        },
                        new
                        {
                            Id = 16,
                            DanceTypeId = 1,
                            Description = "Draught tackle crack Jennys tea cup spirits gun hail-shot starboard rope's end Shiver me timbers topmast. Scourge of the seven seas rope's end bucko hail-shot Sail ho ye knave heave down crow's nest crack Jennys tea cup. Hearties careen deadlights tack cog chantey shrouds lad strike colors lookout. Hempen halter bilge water holystone fluke red ensign Admiral of the Black bilge nipperkin black jack flogging.Draft topmast boatswain hornswaggle killick marooned haul wind cog gally ballast.Clap of thunder red ensign yawl cackle fruit lugger gun plunder Nelsons folly cutlass topsail.",
                            Name = "Rumba Box",
                            SkillLevelId = 1
                        },
                        new
                        {
                            Id = 17,
                            DanceTypeId = 1,
                            Description = "Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Vitae justo eget magna fermentum iaculis eu non. Ultrices gravida dictum fusce ut placerat orci. Consectetur lorem donec massa sapien faucibus et molestie. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Sed arcu non odio euismod lacinia. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Nunc sed blandit libero volutpat sed cras ornare arcu dui. At consectetur lorem donec massa sapien faucibus. Tortor pretium viverra suspendisse potenti nullam ac tortor. Blandit volutpat maecenas volutpat blandit aliquam etiam erat.",
                            Name = "UnderArm Turn",
                            SkillLevelId = 2
                        },
                        new
                        {
                            Id = 18,
                            DanceTypeId = 1,
                            Description = "Trysail quarterdeck Blimey barkadeer furl hang the jib to go on account handsomely gangway reef. Swab hempen halter aft Spanish Main Yellow Jack doubloon sheet schooner belay cog. Lass Plate Fleet Sea Legs Jack Tar Pieces of Eight pirate yo-ho-ho careen line bilge rat. American Main topmast take a caulk ahoy fluke hulk Sink me yawl chandler jib.Black jack barque cackle fruit gangplank matey rope's end strike colors dead men tell no tales gaff capstan. Rope's end gibbet aye take a caulk parley carouser holystone stern jack pressgang. Parrel nipperkin boom wherry coffer belaying pin ahoy Admiral of the Black chase guns tack.Blimey Sea Legs reef bilge rat belay swing the lead Nelsons folly plunder avast landlubber or just lubber.Gangway driver coffer yo - ho - ho jack splice the main brace Buccaneer galleon nipperkin league.",
                            Name = "Rumba Swivels",
                            SkillLevelId = 3
                        });
                });

            modelBuilder.Entity("DanceBlocks.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("DanceTypeId");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("SkillLevelId");

                    b.Property<DateTime>("StudentStartDate");

                    b.Property<int>("UserId");

                    b.Property<string>("UserId1");

                    b.HasKey("Id");

                    b.HasIndex("DanceTypeId");

                    b.HasIndex("SkillLevelId");

                    b.HasIndex("UserId1");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Lucky St. Boston, MA 02101",
                            DanceTypeId = 1,
                            Email = "larry@Bird.com",
                            FirstName = "Larry",
                            IsActive = true,
                            LastName = "Bird",
                            PhoneNumber = "111-111-1111",
                            SkillLevelId = 1,
                            StudentStartDate = new DateTime(2019, 7, 1, 11, 24, 11, 22, DateTimeKind.Local).AddTicks(8762),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 Running st. Greenbow, AL 42101",
                            DanceTypeId = 2,
                            Email = "Jenny@Gump.com",
                            FirstName = "Jenny",
                            IsActive = true,
                            LastName = "Gump",
                            PhoneNumber = "111-111-1112",
                            SkillLevelId = 2,
                            StudentStartDate = new DateTime(2019, 7, 1, 11, 24, 11, 24, DateTimeKind.Local).AddTicks(8770),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "123 Big Mac Ave Oakland, CA 56933",
                            DanceTypeId = 5,
                            Email = "Mark@McGwier.com",
                            FirstName = "Mark",
                            IsActive = true,
                            LastName = "McGwier",
                            PhoneNumber = "111-111-7111",
                            SkillLevelId = 2,
                            StudentStartDate = new DateTime(2019, 7, 1, 11, 24, 11, 24, DateTimeKind.Local).AddTicks(8789),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "123 City Dr. Pawnee, IN. 75101",
                            DanceTypeId = 3,
                            Email = "Leslie@Knope.com",
                            FirstName = "Leslie",
                            IsActive = true,
                            LastName = "Knope",
                            PhoneNumber = "111-111-1122",
                            SkillLevelId = 3,
                            StudentStartDate = new DateTime(2019, 7, 1, 11, 24, 11, 24, DateTimeKind.Local).AddTicks(8793),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DanceBlocks.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "00000000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a00975b-f609-4a86-8fa6-e956daaaaf2e",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHU+Ogj+xILZCFt4I8gQN9/iGNG+UoaUPEFH7jXd+OmdZQX5LuK+wsTBjMOSG0GiDQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com",
                            FirstName = "Admina",
                            LastName = "Straytor"
                        });
                });

            modelBuilder.Entity("DanceBlocks.Models.DanceCategory", b =>
                {
                    b.HasOne("DanceBlocks.Models.Category", "Category")
                        .WithMany("DanceCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DanceBlocks.Models.DanceType", "DanceType")
                        .WithMany("DanceCategories")
                        .HasForeignKey("DanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DanceBlocks.Models.Lesson", b =>
                {
                    b.HasOne("DanceBlocks.Models.Student", "Student")
                        .WithMany("Lessons")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DanceBlocks.Models.LessonStep", b =>
                {
                    b.HasOne("DanceBlocks.Models.Lesson", "Lesson")
                        .WithMany("LessonSteps")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DanceBlocks.Models.Step", "Step")
                        .WithMany("LessonSteps")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DanceBlocks.Models.Step", b =>
                {
                    b.HasOne("DanceBlocks.Models.DanceType", "DanceType")
                        .WithMany()
                        .HasForeignKey("DanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DanceBlocks.Models.SkillLevel", "SkillLevel")
                        .WithMany("Steps")
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DanceBlocks.Models.Student", b =>
                {
                    b.HasOne("DanceBlocks.Models.DanceType", "DanceType")
                        .WithMany()
                        .HasForeignKey("DanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DanceBlocks.Models.SkillLevel", "SkillLevel")
                        .WithMany("Students")
                        .HasForeignKey("SkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DanceBlocks.Models.ApplicationUser", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
